//go:build ignore

// gen_mimetypes generates server/mimetypes_generated.go from the jshttp/mime-db
// database. Run via:
//
//	go generate ./server/...
//
// It fetches db.json from jshttp/mime-db (IANA + Apache + nginx + extras),
// applies the same extension-priority logic as the mime-types npm package
// (IANA > Apache > nginx > none), appends charset where specified, and emits
// a Go source file containing a single map[string]string keyed by lowercase
// file extension (without leading dot).
//
// A small number of overrides are applied after the generated map to ensure
// correct charset annotations for HTML/text types that mime-db omits.
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"os"
	"sort"
	"strings"
	"text/template"
	"time"
)

const mimeDBURL = "https://cdn.jsdelivr.net/npm/mime-db@latest/db.json"

// mimeEntry mirrors the relevant fields in mime-db's db.json
type mimeEntry struct {
	Source      string   `json:"source"`
	Charset     string   `json:"charset"`
	Compressible *bool   `json:"compressible"`
	Extensions  []string `json:"extensions"`
}

// sourcePriority matches mime-types npm package: lower = higher priority
var sourcePriority = map[string]int{
	"iana":   0,
	"apache": 1,
	"nginx":  2,
	"":       3,
}

func priority(src string) int {
	if p, ok := sourcePriority[src]; ok {
		return p
	}
	return 3
}

// overrides applied after the generated map — ensure correct charset for
// types that mime-db leaves unspecified or wrong for browser use.
var overrides = map[string]string{
	"html":  "text/html; charset=utf-8",
	"htm":   "text/html; charset=utf-8",
	"shtml": "text/html; charset=utf-8",
	"xml":   "application/xml; charset=utf-8",
	"txt":   "text/plain; charset=utf-8",
	"csv":   "text/csv; charset=utf-8",
	"md":    "text/markdown; charset=utf-8",
	// Ensure .js/.mjs always get text/javascript (IANA standard, not application/javascript)
	"js":  "text/javascript; charset=utf-8",
	"mjs": "text/javascript; charset=utf-8",
	// .env files (e.g. config.env.js served as JS)
	"env": "text/plain; charset=utf-8",
}

var goFileTemplate = template.Must(template.New("").Parse(`// Code generated by tools/gen_mimetypes/main.go; DO NOT EDIT.
// Source: jshttp/mime-db (IANA + Apache + nginx)
// Generated: {{ .Timestamp }}
// Entries: {{ .Count }}
//
// To regenerate:
//   go generate ./server/...

package server

// generatedMimeTypes maps lowercase file extensions (without leading dot) to
// their canonical MIME type string. Priority: IANA > Apache > nginx > other.
// A small set of overrides ensures correct charset annotations for HTML/text
// types where mime-db omits or differs from browser expectations.
var generatedMimeTypes = map[string]string{
{{ range .Entries }}	{{ printf "%q" .Ext }}: {{ printf "%q" .MIME }},
{{ end }}}
`))

type entry struct {
	Ext  string
	MIME string
}

func main() {
	// Allow overriding output path for testing
	outPath := "server/mimetypes_generated.go"
	if len(os.Args) > 1 {
		outPath = os.Args[1]
	}

	log.Printf("Fetching mime-db from %s", mimeDBURL)
	client := &http.Client{Timeout: 30 * time.Second}
	resp, err := client.Get(mimeDBURL)
	if err != nil {
		log.Fatalf("fetch: %v", err)
	}
	defer resp.Body.Close()

	var db map[string]mimeEntry
	if err := json.NewDecoder(resp.Body).Decode(&db); err != nil {
		log.Fatalf("decode: %v", err)
	}
	log.Printf("Loaded %d MIME entries", len(db))

	// ext -> (mimeString, sourcePriority)
	type candidate struct {
		mime string
		prio int
	}
	extMap := map[string]candidate{}

	for mime, info := range db {
		if len(info.Extensions) == 0 {
			continue
		}
		prio := priority(info.Source)

		// Build full MIME string with charset if specified
		full := mime
		if info.Charset != "" {
			full = mime + "; charset=" + strings.ToLower(info.Charset)
		}

		for _, ext := range info.Extensions {
			ext = strings.ToLower(ext)
			if cur, exists := extMap[ext]; !exists || prio < cur.prio {
				extMap[ext] = candidate{mime: full, prio: prio}
			}
		}
	}

	log.Printf("Built %d extension mappings", len(extMap))

	// Apply overrides
	for ext, mime := range overrides {
		extMap[ext] = candidate{mime: mime, prio: -1}
	}

	// Collect and sort for deterministic output
	entries := make([]entry, 0, len(extMap))
	for ext, c := range extMap {
		entries = append(entries, entry{Ext: ext, MIME: c.mime})
	}
	sort.Slice(entries, func(i, j int) bool {
		return entries[i].Ext < entries[j].Ext
	})

	// Write output
	f, err := os.Create(outPath)
	if err != nil {
		log.Fatalf("create %s: %v", outPath, err)
	}
	defer f.Close()

	err = goFileTemplate.Execute(f, map[string]interface{}{
		"Timestamp": time.Now().UTC().Format("2006-01-02"),
		"Count":     len(entries),
		"Entries":   entries,
	})
	if err != nil {
		log.Fatalf("template: %v", err)
	}

	log.Printf("Wrote %d entries to %s", len(entries), outPath)
	fmt.Printf("OK: %d extension→MIME mappings written to %s\n", len(entries), outPath)
}
