// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddEndpoint(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddEndpoint'](arg1, arg2, arg3, arg4);
}

export function AddEndpointWithConfig(arg1) {
  return window['go']['main']['App']['AddEndpointWithConfig'](arg1);
}

export function AddGroup(arg1) {
  return window['go']['main']['App']['AddGroup'](arg1);
}

export function AddRecentFile(arg1) {
  return window['go']['main']['App']['AddRecentFile'](arg1);
}

export function AddResponse(arg1) {
  return window['go']['main']['App']['AddResponse'](arg1);
}

export function CancelContainerStart(arg1) {
  return window['go']['main']['App']['CancelContainerStart'](arg1);
}

export function ClearRequestLogs() {
  return window['go']['main']['App']['ClearRequestLogs']();
}

export function ClearScriptErrors(arg1) {
  return window['go']['main']['App']['ClearScriptErrors'](arg1);
}

export function DeleteContainer(arg1) {
  return window['go']['main']['App']['DeleteContainer'](arg1);
}

export function DeleteEndpoint(arg1) {
  return window['go']['main']['App']['DeleteEndpoint'](arg1);
}

export function DeleteResponse(arg1) {
  return window['go']['main']['App']['DeleteResponse'](arg1);
}

export function DownloadCACert() {
  return window['go']['main']['App']['DownloadCACert']();
}

export function Emit(arg1, arg2) {
  return window['go']['main']['App']['Emit'](arg1, arg2);
}

export function ExportLogs(arg1) {
  return window['go']['main']['App']['ExportLogs'](arg1);
}

export function GetAllResponseIDsWithErrors() {
  return window['go']['main']['App']['GetAllResponseIDsWithErrors']();
}

export function GetCACertInfo() {
  return window['go']['main']['App']['GetCACertInfo']();
}

export function GetCORSConfig() {
  return window['go']['main']['App']['GetCORSConfig']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetContainerLogs(arg1, arg2) {
  return window['go']['main']['App']['GetContainerLogs'](arg1, arg2);
}

export function GetContainerStats(arg1) {
  return window['go']['main']['App']['GetContainerStats'](arg1);
}

export function GetContainerStatus(arg1) {
  return window['go']['main']['App']['GetContainerStatus'](arg1);
}

export function GetDefaultCertNames() {
  return window['go']['main']['App']['GetDefaultCertNames']();
}

export function GetDefaultContainerHeaders() {
  return window['go']['main']['App']['GetDefaultContainerHeaders']();
}

export function GetEndpointHealth(arg1) {
  return window['go']['main']['App']['GetEndpointHealth'](arg1);
}

export function GetEndpoints() {
  return window['go']['main']['App']['GetEndpoints']();
}

export function GetItems() {
  return window['go']['main']['App']['GetItems']();
}

export function GetRecentFiles() {
  return window['go']['main']['App']['GetRecentFiles']();
}

export function GetRequestLogByID(arg1) {
  return window['go']['main']['App']['GetRequestLogByID'](arg1);
}

export function GetRequestLogDetails(arg1) {
  return window['go']['main']['App']['GetRequestLogDetails'](arg1);
}

export function GetRequestLogs() {
  return window['go']['main']['App']['GetRequestLogs']();
}

export function GetResponses() {
  return window['go']['main']['App']['GetResponses']();
}

export function GetScriptErrors(arg1) {
  return window['go']['main']['App']['GetScriptErrors'](arg1);
}

export function GetSelectedEndpointId() {
  return window['go']['main']['App']['GetSelectedEndpointId']();
}

export function GetServerStatus() {
  return window['go']['main']['App']['GetServerStatus']();
}

export function ImportOpenAPISpecWithDialog(arg1) {
  return window['go']['main']['App']['ImportOpenAPISpecWithDialog'](arg1);
}

export function InstallCACertSystem() {
  return window['go']['main']['App']['InstallCACertSystem']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function LoadConfigFromPath(arg1) {
  return window['go']['main']['App']['LoadConfigFromPath'](arg1);
}

export function LogRequest(arg1) {
  return window['go']['main']['App']['LogRequest'](arg1);
}

export function LogScriptError(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['LogScriptError'](arg1, arg2, arg3, arg4);
}

export function PollEvents() {
  return window['go']['main']['App']['PollEvents']();
}

export function PollRequestLogs() {
  return window['go']['main']['App']['PollRequestLogs']();
}

export function PullDockerImage(arg1) {
  return window['go']['main']['App']['PullDockerImage'](arg1);
}

export function RegenerateCA() {
  return window['go']['main']['App']['RegenerateCA']();
}

export function RemoveRecentFile(arg1) {
  return window['go']['main']['App']['RemoveRecentFile'](arg1);
}

export function ReorderResponses(arg1) {
  return window['go']['main']['App']['ReorderResponses'](arg1);
}

export function RestartContainer(arg1) {
  return window['go']['main']['App']['RestartContainer'](arg1);
}

export function SaveConfig() {
  return window['go']['main']['App']['SaveConfig']();
}

export function SelectCertFile(arg1) {
  return window['go']['main']['App']['SelectCertFile'](arg1);
}

export function SendEvent(arg1, arg2) {
  return window['go']['main']['App']['SendEvent'](arg1, arg2);
}

export function SetCORSConfig(arg1) {
  return window['go']['main']['App']['SetCORSConfig'](arg1);
}

export function SetCertMode(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetCertMode'](arg1, arg2, arg3);
}

export function SetHTTP2Enabled(arg1) {
  return window['go']['main']['App']['SetHTTP2Enabled'](arg1);
}

export function SetHTTPSConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetHTTPSConfig'](arg1, arg2, arg3);
}

export function SetItems(arg1) {
  return window['go']['main']['App']['SetItems'](arg1);
}

export function SetResponses(arg1) {
  return window['go']['main']['App']['SetResponses'](arg1);
}

export function SetSelectedEndpointId(arg1) {
  return window['go']['main']['App']['SetSelectedEndpointId'](arg1);
}

export function StartContainer(arg1) {
  return window['go']['main']['App']['StartContainer'](arg1);
}

export function StartContainers() {
  return window['go']['main']['App']['StartContainers']();
}

export function StartServer(arg1) {
  return window['go']['main']['App']['StartServer'](arg1);
}

export function StopContainer(arg1) {
  return window['go']['main']['App']['StopContainer'](arg1);
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}

export function TestContainerConfig(arg1) {
  return window['go']['main']['App']['TestContainerConfig'](arg1);
}

export function TestProxyConnection(arg1) {
  return window['go']['main']['App']['TestProxyConnection'](arg1);
}

export function UpdateEndpoint(arg1) {
  return window['go']['main']['App']['UpdateEndpoint'](arg1);
}

export function UpdateRequestLog(arg1) {
  return window['go']['main']['App']['UpdateRequestLog'](arg1);
}

export function UpdateResponse(arg1) {
  return window['go']['main']['App']['UpdateResponse'](arg1);
}

export function UpdateResponseByID(arg1) {
  return window['go']['main']['App']['UpdateResponseByID'](arg1);
}

export function ValidateAndInspectDockerImage(arg1) {
  return window['go']['main']['App']['ValidateAndInspectDockerImage'](arg1);
}

export function ValidateCORSHeaderExpression(arg1) {
  return window['go']['main']['App']['ValidateCORSHeaderExpression'](arg1);
}

export function ValidateCORSScript(arg1) {
  return window['go']['main']['App']['ValidateCORSScript'](arg1);
}

export function ValidateDockerImage(arg1) {
  return window['go']['main']['App']['ValidateDockerImage'](arg1);
}
