// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {main} from '../models';

export function AddDomainToSOCKS5Takeover(arg1:string,arg2:boolean):Promise<void>;

export function AddEndpoint(arg1:string,arg2:string,arg3:string,arg4:string):Promise<models.Endpoint>;

export function AddEndpointWithConfig(arg1:Record<string, any>):Promise<models.Endpoint>;

export function AddGroup(arg1:string):Promise<models.ResponseGroup>;

export function AddRecentFile(arg1:string):Promise<void>;

export function AddResponse(arg1:models.MethodResponse):Promise<models.MethodResponse>;

export function AppendSSEEvent(arg1:string,arg2:models.SSEEvent):Promise<void>;

export function AppendWebSocketEvent(arg1:string,arg2:models.WebSocketEvent):Promise<void>;

export function CancelContainerStart(arg1:string):Promise<void>;

export function ClearInactiveRequestLogs():Promise<void>;

export function ClearInactiveRequestLogsForEndpoint(arg1:string):Promise<void>;

export function ClearRequestLogs():Promise<void>;

export function ClearRequestLogsForEndpoint(arg1:string):Promise<void>;

export function ClearScriptErrors(arg1:string):Promise<void>;

export function ClearWSFrames(arg1:string):Promise<void>;

export function CloseSSEStream(arg1:string,arg2:string):Promise<void>;

export function CloseWebSocketConnection(arg1:string,arg2:number,arg3:string,arg4:Error):Promise<void>;

export function DeleteContainer(arg1:string):Promise<void>;

export function DeleteEndpoint(arg1:string):Promise<void>;

export function DeleteResponse(arg1:string):Promise<void>;

export function DownloadCACert():Promise<string>;

export function Emit(arg1:string,arg2:any):Promise<void>;

export function ExportLogs(arg1:string):Promise<void>;

export function ExportLogsAsCurl(arg1:string,arg2:string):Promise<void>;

export function ExportLogsAsHAR(arg1:string,arg2:string):Promise<void>;

export function ExportWSTrace(arg1:string):Promise<void>;

export function FrontendLog(arg1:string):Promise<void>;

export function GetAllResponseIDsWithErrors():Promise<Array<string>>;

export function GetCACertInfo():Promise<models.CACertInfo>;

export function GetCACertInstallScript():Promise<Record<string, string>>;

export function GetCORSConfig():Promise<models.CORSConfig>;

export function GetConfig():Promise<models.AppConfig>;

export function GetContainerLogs(arg1:string,arg2:number):Promise<string>;

export function GetContainerStats(arg1:string):Promise<models.ContainerStats>;

export function GetContainerStatus(arg1:string):Promise<models.ContainerStatus>;

export function GetCurrentConfigPath():Promise<string>;

export function GetDNSOverrides():Promise<models.DNSOverrideConfig>;

export function GetDNSProviders():Promise<Record<string, models.DNSProvider>>;

export function GetDefaultCertNames():Promise<Array<string>>;

export function GetDefaultContainerHeaders():Promise<Array<models.HeaderManipulation>>;

export function GetEndpointHealth(arg1:string):Promise<models.HealthStatus>;

export function GetEndpoints():Promise<Array<models.Endpoint>>;

export function GetItems():Promise<Array<models.ResponseItem>>;

export function GetLogCount():Promise<number>;

export function GetLogPage(arg1:number,arg2:number):Promise<Array<models.RequestLogSummary>>;

export function GetRecentFiles():Promise<Array<models.RecentFile>>;

export function GetRequestLogByID(arg1:string):Promise<models.RequestLog>;

export function GetRequestLogDetails(arg1:string):Promise<models.RequestLog>;

export function GetRequestLogs():Promise<Array<models.RequestLogSummary>>;

export function GetResponses():Promise<Array<models.MethodResponse>>;

export function GetRuntimeOS():Promise<string>;

export function GetSOCKS5Config():Promise<main.SOCKS5ConfigResponse>;

export function GetSOCKS5Domains():Promise<Array<models.SOCKS5DomainInfo>>;

export function GetScriptErrors(arg1:string):Promise<Array<main.ScriptErrorLog>>;

export function GetSelectedEndpointId():Promise<string>;

export function GetServerStatus():Promise<main.ServerStatus>;

export function GetWSCaptureBytes():Promise<number>;

export function ImportOpenAPISpecWithDialog(arg1:boolean):Promise<models.AppConfig>;

export function InstallCACertCurrentUser():Promise<void>;

export function InstallCACertSystem():Promise<void>;

export function InstallCACertSystemElevated():Promise<void>;

export function IsDirty():Promise<boolean>;

export function LoadConfig():Promise<models.AppConfig>;

export function LoadConfigFromPath(arg1:string):Promise<models.AppConfig>;

export function LogRequest(arg1:models.RequestLog):Promise<void>;

export function LogScriptError(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function MarkClean():Promise<void>;

export function MarkDirty():Promise<void>;

export function MarkSSEOpen(arg1:string,arg2:string):Promise<void>;

export function PollEvents():Promise<Array<main.Event>>;

export function PollRequestLogs():Promise<Array<models.RequestLogSummary>>;

export function PullDockerImage(arg1:string):Promise<void>;

export function RegenerateCA():Promise<void>;

export function RegisterWSConnection(arg1:string,arg2:any,arg3:any):Promise<void>;

export function RemoveRecentFile(arg1:string):Promise<void>;

export function ReorderEndpoints(arg1:Array<string>):Promise<void>;

export function ReorderResponses(arg1:Array<string>):Promise<void>;

export function RestartContainer(arg1:string):Promise<void>;

export function SaveConfig():Promise<void>;

export function SaveCurrentConfig():Promise<void>;

export function SelectCertFile(arg1:string):Promise<string>;

export function SendEvent(arg1:string,arg2:any):Promise<void>;

export function SetItems(arg1:Array<models.ResponseItem>):Promise<void>;

export function SetOverlaySimulationMode(arg1:string,arg2:models.OverlaySimConfig):Promise<void>;

export function SetOverlayTimeouts(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SetProxySimulationMode(arg1:string,arg2:models.OverlaySimConfig):Promise<void>;

export function SetProxyTimeouts(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SetResponses(arg1:Array<models.MethodResponse>):Promise<void>;

export function SetSelectedEndpointId(arg1:string):Promise<void>;

export function SetWSConnectionBlocked(arg1:string,arg2:boolean):Promise<void>;

export function StartContainer(arg1:string):Promise<void>;

export function StartContainers():Promise<void>;

export function StartServer(arg1:number):Promise<void>;

export function StopContainer(arg1:string):Promise<void>;

export function StopServer():Promise<void>;

export function TerminateWSConnection(arg1:string):Promise<void>;

export function TestContainerConfig(arg1:Record<string, any>):Promise<main.ContainerTestResult>;

export function TestProxyConnection(arg1:string):Promise<void>;

export function UpdateDNSOverrides(arg1:models.DNSOverrideConfig):Promise<void>;

export function UpdateEndpoint(arg1:models.Endpoint):Promise<void>;

export function UpdateRequestLog(arg1:models.RequestLog):Promise<void>;

export function UpdateResponse(arg1:models.MethodResponse):Promise<void>;

export function UpdateResponseByID(arg1:models.MethodResponse):Promise<void>;

export function UpdateServerSettings(arg1:models.ServerSettings):Promise<void>;

export function ValidateAndInspectDockerImage(arg1:string):Promise<models.DockerImageInfo>;

export function ValidateCORSHeaderExpression(arg1:string):Promise<void>;

export function ValidateCORSScript(arg1:string):Promise<void>;

export function ValidateDockerImage(arg1:string):Promise<void>;
