// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDomainToSOCKS5Takeover(arg1, arg2) {
  return window['go']['main']['App']['AddDomainToSOCKS5Takeover'](arg1, arg2);
}

export function AddEndpoint(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddEndpoint'](arg1, arg2, arg3, arg4);
}

export function AddEndpointWithConfig(arg1) {
  return window['go']['main']['App']['AddEndpointWithConfig'](arg1);
}

export function AddGroup(arg1) {
  return window['go']['main']['App']['AddGroup'](arg1);
}

export function AddRecentFile(arg1) {
  return window['go']['main']['App']['AddRecentFile'](arg1);
}

export function AddResponse(arg1) {
  return window['go']['main']['App']['AddResponse'](arg1);
}

export function AppendSSEEvent(arg1, arg2) {
  return window['go']['main']['App']['AppendSSEEvent'](arg1, arg2);
}

export function AppendWebSocketEvent(arg1, arg2) {
  return window['go']['main']['App']['AppendWebSocketEvent'](arg1, arg2);
}

export function CancelContainerStart(arg1) {
  return window['go']['main']['App']['CancelContainerStart'](arg1);
}

export function ClearInactiveRequestLogs() {
  return window['go']['main']['App']['ClearInactiveRequestLogs']();
}

export function ClearInactiveRequestLogsForEndpoint(arg1) {
  return window['go']['main']['App']['ClearInactiveRequestLogsForEndpoint'](arg1);
}

export function ClearRequestLogs() {
  return window['go']['main']['App']['ClearRequestLogs']();
}

export function ClearRequestLogsForEndpoint(arg1) {
  return window['go']['main']['App']['ClearRequestLogsForEndpoint'](arg1);
}

export function ClearScriptErrors(arg1) {
  return window['go']['main']['App']['ClearScriptErrors'](arg1);
}

export function ClearWSFrames(arg1) {
  return window['go']['main']['App']['ClearWSFrames'](arg1);
}

export function CloseSSEStream(arg1, arg2) {
  return window['go']['main']['App']['CloseSSEStream'](arg1, arg2);
}

export function CloseWebSocketConnection(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CloseWebSocketConnection'](arg1, arg2, arg3, arg4);
}

export function DeleteContainer(arg1) {
  return window['go']['main']['App']['DeleteContainer'](arg1);
}

export function DeleteEndpoint(arg1) {
  return window['go']['main']['App']['DeleteEndpoint'](arg1);
}

export function DeleteResponse(arg1) {
  return window['go']['main']['App']['DeleteResponse'](arg1);
}

export function DownloadCACert() {
  return window['go']['main']['App']['DownloadCACert']();
}

export function Emit(arg1, arg2) {
  return window['go']['main']['App']['Emit'](arg1, arg2);
}

export function ExportLogs(arg1) {
  return window['go']['main']['App']['ExportLogs'](arg1);
}

export function ExportLogsAsCurl(arg1, arg2) {
  return window['go']['main']['App']['ExportLogsAsCurl'](arg1, arg2);
}

export function ExportLogsAsHAR(arg1, arg2) {
  return window['go']['main']['App']['ExportLogsAsHAR'](arg1, arg2);
}

export function ExportWSTrace(arg1) {
  return window['go']['main']['App']['ExportWSTrace'](arg1);
}

export function FrontendLog(arg1) {
  return window['go']['main']['App']['FrontendLog'](arg1);
}

export function GetAllResponseIDsWithErrors() {
  return window['go']['main']['App']['GetAllResponseIDsWithErrors']();
}

export function GetCACertInfo() {
  return window['go']['main']['App']['GetCACertInfo']();
}

export function GetCACertInstallScript() {
  return window['go']['main']['App']['GetCACertInstallScript']();
}

export function GetCORSConfig() {
  return window['go']['main']['App']['GetCORSConfig']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetContainerLogs(arg1, arg2) {
  return window['go']['main']['App']['GetContainerLogs'](arg1, arg2);
}

export function GetContainerStats(arg1) {
  return window['go']['main']['App']['GetContainerStats'](arg1);
}

export function GetContainerStatus(arg1) {
  return window['go']['main']['App']['GetContainerStatus'](arg1);
}

export function GetCurrentConfigPath() {
  return window['go']['main']['App']['GetCurrentConfigPath']();
}

export function GetDNSOverrides() {
  return window['go']['main']['App']['GetDNSOverrides']();
}

export function GetDNSProviders() {
  return window['go']['main']['App']['GetDNSProviders']();
}

export function GetDefaultCertNames() {
  return window['go']['main']['App']['GetDefaultCertNames']();
}

export function GetDefaultContainerHeaders() {
  return window['go']['main']['App']['GetDefaultContainerHeaders']();
}

export function GetEndpointHealth(arg1) {
  return window['go']['main']['App']['GetEndpointHealth'](arg1);
}

export function GetEndpoints() {
  return window['go']['main']['App']['GetEndpoints']();
}

export function GetItems() {
  return window['go']['main']['App']['GetItems']();
}

export function GetRecentFiles() {
  return window['go']['main']['App']['GetRecentFiles']();
}

export function GetRequestLogByID(arg1) {
  return window['go']['main']['App']['GetRequestLogByID'](arg1);
}

export function GetRequestLogDetails(arg1) {
  return window['go']['main']['App']['GetRequestLogDetails'](arg1);
}

export function GetRequestLogs() {
  return window['go']['main']['App']['GetRequestLogs']();
}

export function GetResponses() {
  return window['go']['main']['App']['GetResponses']();
}

export function GetRuntimeOS() {
  return window['go']['main']['App']['GetRuntimeOS']();
}

export function GetSOCKS5Config() {
  return window['go']['main']['App']['GetSOCKS5Config']();
}

export function GetSOCKS5Domains() {
  return window['go']['main']['App']['GetSOCKS5Domains']();
}

export function GetScriptErrors(arg1) {
  return window['go']['main']['App']['GetScriptErrors'](arg1);
}

export function GetSelectedEndpointId() {
  return window['go']['main']['App']['GetSelectedEndpointId']();
}

export function GetServerStatus() {
  return window['go']['main']['App']['GetServerStatus']();
}

export function GetWSCaptureBytes() {
  return window['go']['main']['App']['GetWSCaptureBytes']();
}

export function ImportOpenAPISpecWithDialog(arg1) {
  return window['go']['main']['App']['ImportOpenAPISpecWithDialog'](arg1);
}

export function InstallCACertCurrentUser() {
  return window['go']['main']['App']['InstallCACertCurrentUser']();
}

export function InstallCACertSystem() {
  return window['go']['main']['App']['InstallCACertSystem']();
}

export function InstallCACertSystemElevated() {
  return window['go']['main']['App']['InstallCACertSystemElevated']();
}

export function IsDirty() {
  return window['go']['main']['App']['IsDirty']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function LoadConfigFromPath(arg1) {
  return window['go']['main']['App']['LoadConfigFromPath'](arg1);
}

export function LogRequest(arg1) {
  return window['go']['main']['App']['LogRequest'](arg1);
}

export function LogScriptError(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['LogScriptError'](arg1, arg2, arg3, arg4);
}

export function MarkClean() {
  return window['go']['main']['App']['MarkClean']();
}

export function MarkDirty() {
  return window['go']['main']['App']['MarkDirty']();
}

export function MarkSSEOpen(arg1, arg2) {
  return window['go']['main']['App']['MarkSSEOpen'](arg1, arg2);
}

export function PollEvents() {
  return window['go']['main']['App']['PollEvents']();
}

export function PollRequestLogs() {
  return window['go']['main']['App']['PollRequestLogs']();
}

export function PullDockerImage(arg1) {
  return window['go']['main']['App']['PullDockerImage'](arg1);
}

export function RegenerateCA() {
  return window['go']['main']['App']['RegenerateCA']();
}

export function RegisterWSConnection(arg1, arg2, arg3) {
  return window['go']['main']['App']['RegisterWSConnection'](arg1, arg2, arg3);
}

export function RemoveRecentFile(arg1) {
  return window['go']['main']['App']['RemoveRecentFile'](arg1);
}

export function ReorderEndpoints(arg1) {
  return window['go']['main']['App']['ReorderEndpoints'](arg1);
}

export function ReorderResponses(arg1) {
  return window['go']['main']['App']['ReorderResponses'](arg1);
}

export function RestartContainer(arg1) {
  return window['go']['main']['App']['RestartContainer'](arg1);
}

export function SaveConfig() {
  return window['go']['main']['App']['SaveConfig']();
}

export function SaveCurrentConfig() {
  return window['go']['main']['App']['SaveCurrentConfig']();
}

export function SelectCertFile(arg1) {
  return window['go']['main']['App']['SelectCertFile'](arg1);
}

export function SendEvent(arg1, arg2) {
  return window['go']['main']['App']['SendEvent'](arg1, arg2);
}

export function SetItems(arg1) {
  return window['go']['main']['App']['SetItems'](arg1);
}

export function SetOverlaySimulationMode(arg1, arg2) {
  return window['go']['main']['App']['SetOverlaySimulationMode'](arg1, arg2);
}

export function SetOverlayTimeouts(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetOverlayTimeouts'](arg1, arg2, arg3);
}

export function SetProxySimulationMode(arg1, arg2) {
  return window['go']['main']['App']['SetProxySimulationMode'](arg1, arg2);
}

export function SetProxyTimeouts(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetProxyTimeouts'](arg1, arg2, arg3);
}

export function SetResponses(arg1) {
  return window['go']['main']['App']['SetResponses'](arg1);
}

export function SetSelectedEndpointId(arg1) {
  return window['go']['main']['App']['SetSelectedEndpointId'](arg1);
}

export function SetWSConnectionBlocked(arg1, arg2) {
  return window['go']['main']['App']['SetWSConnectionBlocked'](arg1, arg2);
}

export function StartContainer(arg1) {
  return window['go']['main']['App']['StartContainer'](arg1);
}

export function StartContainers() {
  return window['go']['main']['App']['StartContainers']();
}

export function StartServer(arg1) {
  return window['go']['main']['App']['StartServer'](arg1);
}

export function StopContainer(arg1) {
  return window['go']['main']['App']['StopContainer'](arg1);
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}

export function TerminateWSConnection(arg1) {
  return window['go']['main']['App']['TerminateWSConnection'](arg1);
}

export function TestContainerConfig(arg1) {
  return window['go']['main']['App']['TestContainerConfig'](arg1);
}

export function TestProxyConnection(arg1) {
  return window['go']['main']['App']['TestProxyConnection'](arg1);
}

export function UpdateDNSOverrides(arg1) {
  return window['go']['main']['App']['UpdateDNSOverrides'](arg1);
}

export function UpdateEndpoint(arg1) {
  return window['go']['main']['App']['UpdateEndpoint'](arg1);
}

export function UpdateRequestLog(arg1) {
  return window['go']['main']['App']['UpdateRequestLog'](arg1);
}

export function UpdateResponse(arg1) {
  return window['go']['main']['App']['UpdateResponse'](arg1);
}

export function UpdateResponseByID(arg1) {
  return window['go']['main']['App']['UpdateResponseByID'](arg1);
}

export function UpdateServerSettings(arg1) {
  return window['go']['main']['App']['UpdateServerSettings'](arg1);
}

export function ValidateAndInspectDockerImage(arg1) {
  return window['go']['main']['App']['ValidateAndInspectDockerImage'](arg1);
}

export function ValidateCORSHeaderExpression(arg1) {
  return window['go']['main']['App']['ValidateCORSHeaderExpression'](arg1);
}

export function ValidateCORSScript(arg1) {
  return window['go']['main']['App']['ValidateCORSScript'](arg1);
}

export function ValidateDockerImage(arg1) {
  return window['go']['main']['App']['ValidateDockerImage'](arg1);
}
