// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {main} from '../models';

export function AddGroup(arg1:string):Promise<models.ResponseGroup>;

export function AddResponse(arg1:models.MethodResponse):Promise<models.MethodResponse>;

export function ClearRequestLogs():Promise<void>;

export function DeleteResponse(arg1:string):Promise<void>;

export function DownloadCACert():Promise<string>;

export function ExportLogs(arg1:string):Promise<void>;

export function GetCACertInfo():Promise<models.CACertInfo>;

export function GetCORSConfig():Promise<models.CORSConfig>;

export function GetConfig():Promise<models.AppConfig>;

export function GetDefaultCertNames():Promise<Array<string>>;

export function GetItems():Promise<Array<models.ResponseItem>>;

export function GetRequestLogByID(arg1:string):Promise<models.RequestLog>;

export function GetRequestLogs():Promise<Array<models.RequestLog>>;

export function GetResponses():Promise<Array<models.MethodResponse>>;

export function GetServerStatus():Promise<main.ServerStatus>;

export function ImportOpenAPISpecWithDialog(arg1:boolean):Promise<models.AppConfig>;

export function InstallCACertSystem():Promise<void>;

export function LoadConfig():Promise<models.AppConfig>;

export function LogRequest(arg1:models.RequestLog):Promise<void>;

export function RegenerateCA():Promise<void>;

export function ReorderResponses(arg1:Array<string>):Promise<void>;

export function SaveConfig():Promise<void>;

export function SelectCertFile(arg1:string):Promise<string>;

export function SetCORSConfig(arg1:models.CORSConfig):Promise<void>;

export function SetCertMode(arg1:string,arg2:models.CertPaths,arg3:Array<string>):Promise<void>;

export function SetHTTP2Enabled(arg1:boolean):Promise<void>;

export function SetHTTPSConfig(arg1:boolean,arg2:number,arg3:boolean):Promise<void>;

export function SetItems(arg1:Array<models.ResponseItem>):Promise<void>;

export function SetResponses(arg1:Array<models.MethodResponse>):Promise<void>;

export function StartServer(arg1:number):Promise<void>;

export function StopServer():Promise<void>;

export function UpdateResponse(arg1:models.MethodResponse):Promise<void>;

export function UpdateResponseByID(arg1:models.MethodResponse):Promise<void>;

export function ValidateCORSHeaderExpression(arg1:string):Promise<void>;

export function ValidateCORSScript(arg1:string):Promise<void>;
