// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddGroup(arg1) {
  return window['go']['main']['App']['AddGroup'](arg1);
}

export function AddResponse(arg1) {
  return window['go']['main']['App']['AddResponse'](arg1);
}

export function ClearRequestLogs() {
  return window['go']['main']['App']['ClearRequestLogs']();
}

export function DeleteResponse(arg1) {
  return window['go']['main']['App']['DeleteResponse'](arg1);
}

export function DownloadCACert() {
  return window['go']['main']['App']['DownloadCACert']();
}

export function ExportLogs(arg1) {
  return window['go']['main']['App']['ExportLogs'](arg1);
}

export function GetCACertInfo() {
  return window['go']['main']['App']['GetCACertInfo']();
}

export function GetCORSConfig() {
  return window['go']['main']['App']['GetCORSConfig']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDefaultCertNames() {
  return window['go']['main']['App']['GetDefaultCertNames']();
}

export function GetItems() {
  return window['go']['main']['App']['GetItems']();
}

export function GetRequestLogByID(arg1) {
  return window['go']['main']['App']['GetRequestLogByID'](arg1);
}

export function GetRequestLogs() {
  return window['go']['main']['App']['GetRequestLogs']();
}

export function GetResponses() {
  return window['go']['main']['App']['GetResponses']();
}

export function GetServerStatus() {
  return window['go']['main']['App']['GetServerStatus']();
}

export function ImportOpenAPISpecWithDialog(arg1) {
  return window['go']['main']['App']['ImportOpenAPISpecWithDialog'](arg1);
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function LogRequest(arg1) {
  return window['go']['main']['App']['LogRequest'](arg1);
}

export function RegenerateCA() {
  return window['go']['main']['App']['RegenerateCA']();
}

export function ReorderResponses(arg1) {
  return window['go']['main']['App']['ReorderResponses'](arg1);
}

export function SaveConfig() {
  return window['go']['main']['App']['SaveConfig']();
}

export function SelectCertFile(arg1) {
  return window['go']['main']['App']['SelectCertFile'](arg1);
}

export function SetCORSConfig(arg1) {
  return window['go']['main']['App']['SetCORSConfig'](arg1);
}

export function SetCertMode(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetCertMode'](arg1, arg2, arg3);
}

export function SetHTTPSConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetHTTPSConfig'](arg1, arg2, arg3);
}

export function SetItems(arg1) {
  return window['go']['main']['App']['SetItems'](arg1);
}

export function SetResponses(arg1) {
  return window['go']['main']['App']['SetResponses'](arg1);
}

export function StartServer(arg1) {
  return window['go']['main']['App']['StartServer'](arg1);
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}

export function UpdateResponse(arg1) {
  return window['go']['main']['App']['UpdateResponse'](arg1);
}

export function UpdateResponseByID(arg1) {
  return window['go']['main']['App']['UpdateResponseByID'](arg1);
}

export function ValidateCORSHeaderExpression(arg1) {
  return window['go']['main']['App']['ValidateCORSHeaderExpression'](arg1);
}

export function ValidateCORSScript(arg1) {
  return window['go']['main']['App']['ValidateCORSScript'](arg1);
}
